sudo: required
services:
  - docker

before_install:
  - docker build -t sgdocker2020/docker-react -f Dockerfile.dev .

script:
  - docker run sgdocker2020/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "React-frontend"
  env: "React-frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-272869797195"
  bucket_path: "React-frontend"
  on:
    branch: main
  access_key_id: "AKIAT7CCOVVFQERUIMXK"